USE master;
GO

CREATE DATABASE DB_DOTNET_PLENO;
GO

USE DB_DOTNET_PLENO;
GO

CREATE TABLE TB_TIPO_PESSOA (
    ID TINYINT PRIMARY KEY IDENTITY(1,1),
    TIPO NVARCHAR(7) NOT NULL CHECK (TIPO IN ('PF', 'PJ'))
);

CREATE TABLE TB_PESSOA (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ID_TIPO_PESSOA TINYINT NOT NULL,
    NOME NVARCHAR(255) NOT NULL,
    DOCUMENTO NVARCHAR(31) UNIQUE NOT NULL,
    CONSTRAINT FK_TIPO_PESSOA FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TB_TIPO_PESSOA(ID)
);

CREATE TABLE TB_ENDERECO (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    CEP NVARCHAR(15) NOT NULL,
    LOGRADOURO NVARCHAR(255) NOT NULL,
    NUMERO NVARCHAR(7),
    BAIRRO NVARCHAR(63) NOT NULL,
    CIDADE NVARCHAR(31) NOT NULL,
    UF NVARCHAR(2) NOT NULL
);

CREATE TABLE TB_PESSOA_ENDERECO (
    ID_PESSOA BIGINT NOT NULL,
    ID_ENDERECO BIGINT NOT NULL,
    CONSTRAINT PK_TB_PESSOA_ENDERECO PRIMARY KEY (ID_PESSOA, ID_ENDERECO),
    CONSTRAINT FK_TB_PESSOA_ENDERECO_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID),
    CONSTRAINT FK_TB_PESSOA_ENDERECO_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO(ID)
);

CREATE TABLE TB_PESSOA_LISTA (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ID_PESSOA BIGINT NOT NULL,
    LISTA NVARCHAR(127) NOT NULL,
    CONSTRAINT FK_TB_PESSOA_LISTA_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID)
);

CREATE INDEX IDX_TB_PESSOA_DOCUMENTO ON TB_PESSOA (DOCUMENTO);
